apiVersion: batch/v1
kind: CronJob
metadata:
  name: covid-19-data-puller
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: covid-19-data-puller
            image: "pankajackson/covid19esdatapuller:03"
            imagePullPolicy: Always
            env:
            - name: "OWID_SOURCE_DATA_URL"
              value: "https://covid.ourworldindata.org/data/owid-covid-data.csv"
            - name: "ES_URL"
              value: "elasticsearch:9200"
            - name: "ES_INDEX"
              value: "test"
          restartPolicy: OnFailure